# Generated by Django 3.2.6 on 2021-08-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210811_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='province',
            field=models.CharField(blank=True, max_length=75, verbose_name='State/Province'),
        ),
    ]
