# Generated by Django 3.2.6 on 2021-08-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img_height',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='event',
            name='img_width',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, height_field='img_height', null=True, upload_to='', width_field='img_width'),
        ),
    ]
