# Generated by Django 3.2.6 on 2021-08-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20210811_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='event',
            name='img_width',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
