# Generated by Django 3.2.6 on 2021-08-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_artist_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
