# Generated by Django 3.2.6 on 2021-08-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_artist_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='event',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='email',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='social_media',
        ),
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
