# Generated by Django 3.2.6 on 2021-08-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20210817_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
