# Generated by Django 3.2.6 on 2021-08-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
