# Generated by Django 3.2.6 on 2021-09-05 22:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 5, 22, 38, 55, 207516, tzinfo=utc)),
        ),
    ]
